name: ECR Image
on:
  push:
    branches: ["reggie"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ github.ref_name }}
    env:
      STAGE_NAME: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - run: aws --version
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800
      - name: Upload connector image if needed
        run: ${PWD}/scripts/connector-image.sh
